/**
 * This file is intended to be generated by `openapi-typescript` from `openapi.json`.
 * Do not edit manually.
 */

export interface paths {
  '/v1/auth/login': {
    post: operations['AuthController_login'];
  };
  '/v1/auth/verify-login-otp': {
    post: operations['AuthController_verifyLoginOtp'];
  };
  '/v1/auth/verify-2fa': {
    post: operations['AuthController_verifyTwoFactor'];
  };
  '/v1/auth/refresh': {
    post: operations['AuthController_refreshToken'];
  };
  '/v1/transactions/deposit': {
    post: operations['TransactionsController_createDeposit'];
  };
  '/v1/transactions/withdraw': {
    post: operations['TransactionsController_createWithdrawal'];
  };
  '/v1/transactions': {
    get: operations['TransactionsController_findAll'];
  };
  '/v1/transactions/{id}': {
    get: operations['TransactionsController_findOne'];
  };
  '/v1/transactions/{id}/verify': {
    post: operations['TransactionsController_verifyTransaction'];
  };
  '/v1/exchange-rates': {
    get: operations['ExchangeRatesController_getRate'];
  };
}

export interface components {
  schemas: {
    LoginDto: {
      email: string;
      password: string;
    };
    MessageResponse: {
      message: string;
    };
    VerifyLoginOtpDto: {
      email: string;
      otp: string;
    };
    VerifyTwoFactorDto: {
      twoFactorToken: string;
      totpCode: string;
    };
    RefreshTokenRequestDto: {
      refreshToken: string;
    };
    AuthTokensDto: {
      accessToken: string;
      refreshToken?: string;
      expiresIn: number;
    };
    TwoFactorChallengeDto: {
      requiresTwoFactor: boolean;
      twoFactorToken: string;
      message: string;
    };
    VerifyLoginOtpResponseDto:
      | components['schemas']['AuthTokensDto']
      | components['schemas']['TwoFactorChallengeDto'];
    TransactionType: 'deposit' | 'withdrawal';
    TransactionStatus: 'pending' | 'completed' | 'failed';
    CreateDepositDto: {
      amount: number;
      currency: string;
      sourceAddress: string;
    };
    CreateWithdrawalDto: {
      amount: number;
      currency: string;
      destinationAddress: string;
      beneficiaryId?: string;
    };
    TransactionResponseDto: {
      id: string;
      userId: string;
      type: components['schemas']['TransactionType'];
      amount: string;
      currency: string;
      currencySymbol?: string;
      currencyDisplayName?: string;
      rate?: string;
      status: components['schemas']['TransactionStatus'];
      txHash?: string;
      failureReason?: string;
      feeAmount?: string;
      feeCurrency?: string;
      createdAt: string;
      updatedAt: string;
      sourceAddress?: string;
      destinationAddress?: string;
    };
    TransactionListResponseDto: {
      transactions: components['schemas']['TransactionResponseDto'][];
      total: number;
    };
    ExchangeRateResponseDto: {
      from: string;
      to: string;
      rate: number;
      fetchedAt?: string;
      expiresAt?: string;
    };
    ApiEnvelope_MessageResponse: {
      success: boolean;
      data: components['schemas']['MessageResponse'];
      timestamp: string;
    };
    ApiEnvelope_AuthTokensDto: {
      success: boolean;
      data: components['schemas']['AuthTokensDto'];
      timestamp: string;
    };
    ApiEnvelope_VerifyLoginOtpResponseDto: {
      success: boolean;
      data: components['schemas']['VerifyLoginOtpResponseDto'];
      timestamp: string;
    };
    ApiEnvelope_TransactionResponseDto: {
      success: boolean;
      data: components['schemas']['TransactionResponseDto'];
      timestamp: string;
    };
    ApiEnvelope_TransactionListResponseDto: {
      success: boolean;
      data: components['schemas']['TransactionListResponseDto'];
      timestamp: string;
    };
    ApiEnvelope_ExchangeRateResponseDto: {
      success: boolean;
      data: components['schemas']['ExchangeRateResponseDto'];
      timestamp: string;
    };
  };
}

export interface operations {
  AuthController_login: {
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['ApiEnvelope_MessageResponse'];
        };
      };
    };
  };
  AuthController_verifyLoginOtp: {
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyLoginOtpDto'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['ApiEnvelope_VerifyLoginOtpResponseDto'];
        };
      };
    };
  };
  AuthController_verifyTwoFactor: {
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyTwoFactorDto'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['ApiEnvelope_AuthTokensDto'];
        };
      };
    };
  };
  AuthController_refreshToken: {
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenRequestDto'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['ApiEnvelope_AuthTokensDto'];
        };
      };
    };
  };
  TransactionsController_createDeposit: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateDepositDto'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['ApiEnvelope_TransactionResponseDto'];
        };
      };
    };
  };
  TransactionsController_createWithdrawal: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateWithdrawalDto'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['ApiEnvelope_TransactionResponseDto'];
        };
      };
    };
  };
  TransactionsController_findAll: {
    parameters: {
      query?: {
        type?: components['schemas']['TransactionType'];
        status?: components['schemas']['TransactionStatus'];
        currency?: string;
        page?: number;
        limit?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['ApiEnvelope_TransactionListResponseDto'];
        };
      };
    };
  };
  TransactionsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['ApiEnvelope_TransactionResponseDto'];
        };
      };
    };
  };
  TransactionsController_verifyTransaction: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['ApiEnvelope_TransactionResponseDto'];
        };
      };
    };
  };
  ExchangeRatesController_getRate: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['ApiEnvelope_ExchangeRateResponseDto'];
        };
      };
    };
  };
}
